//Get all characters.
GET http://localhost:4000/api/characters/

###
//Get a character by his id.
GET http://localhost:4000/api/characters/6227792a93675f2014aacd85

###
//Create a new character.
POST http://localhost:4000/api/characters/
Content-Type: application/json

{
    "name": "Jojo",
    "race": "Human",
    "gender": "Male",
    "age": 28,
    "hp": 500,
    "mana": 1000,
    "level": 10,
    "class": "Warrior",
    "skills": 
    [
        {
            "name": "Berserk", 
            "effectDuration": 60, 
            "manaCost": 10, 
            "cooldown": 300
        },
        {
            "name": "Berserker Armor", 
            "effectDuration": 120, 
            "manaCost": 100, 
            "cooldown": 240
        }
    ]
}
###
//Update a character by his id.
PATCH http://localhost:4000/api/characters/62286f34fe5da79c38c050b9
Content-Type: application/json

{
    "name": "Alice",
    "age": 21
}
###
//Delete a character by his id.
DELETE http://localhost:4000/api/characters/62286f34fe5da79c38c050b9